CREATE TABLE IF NOT EXISTS "companies" (
	"id" text PRIMARY KEY NOT NULL,
	"co_name" text NOT NULL,
	"co_website_url" text,
	"co_description" text,
	"co_one_liner" text NOT NULL,
	"co_country" text NOT NULL,
	"co_city" text NOT NULL,
	"co_product_status" text NOT NULL,
	"co_customer_count" text,
	"co_monthly_revenue" text,
	"co_annual_revenue" text,
	"co_annual_expense" text,
	"co_expected_valuation" integer,
	"co_fundraising_amount" integer,
	"co_past_fundraising_info" text,
	"co_funding_round" text NOT NULL,
	"co_industry_1" text,
	"co_industry_2" text,
	"co_industry_3" text,
	"user_id" text NOT NULL,
	"founder_first_name_1" text NOT NULL,
	"founder_last_name_1" text NOT NULL,
	"founder_title_1" text NOT NULL,
	"founder_bio_1" text NOT NULL,
	"founder_twitter_url_1" text,
	"founder_linkedin_url_1" text,
	"founder_first_name_2" text,
	"founder_last_name_2" text,
	"founder_title_2" text,
	"founder_bio_2" text,
	"founder_twitter_url_2" text,
	"founder_linkedin_url_2" text,
	"founder_first_name_3" text,
	"founder_last_name_3" text,
	"founder_title_3" text,
	"founder_bio_3" text,
	"founder_twitter_url_3" text,
	"founder_linkedin_url_3" text,
	"founder_first_name_4" text,
	"founder_last_name_4" text,
	"founder_title_4" text,
	"founder_bio_4" text,
	"founder_twitter_url_4" text,
	"founder_linkedin_url_4" text,
	"founder_first_name_5" text,
	"founder_last_name_5" text,
	"founder_title_5" text,
	"founder_bio_5" text,
	"founder_twitter_url_5" text,
	"founder_linkedin_url_5" text
);
