CREATE TABLE IF NOT EXISTS "companies" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"co_name" text NOT NULL,
	"co_website_url" text,
	"co_no_website_url" boolean,
	"co_industry_1" text,
	"co_industry_2" text,
	"co_industry_3" text,
	"co_description" text,
	"co_one_liner" text,
	"co_country" text NOT NULL,
	"co_city" text NOT NULL,
	"co_product_status" text,
	"co_pre_revenue" boolean,
	"co_customer_count" text,
	"co_monthly_revenue" text,
	"co_annual_revenue" text,
	"co_annual_expense" text,
	"founder_first_name_1" text,
	"founder_last_name_1" text,
	"founder_title_1" text,
	"founder_bio_1" text,
	"founder_twitter_url_1" text,
	"founder_linkedin_url_1" text,
	"founder_first_name_2" text,
	"founder_last_name_2" text,
	"founder_title_2" text,
	"founder_bio_2" text,
	"founder_twitter_url_2" text,
	"founder_linkedin_url_2" text,
	"founder_first_name_3" text,
	"founder_last_name_3" text,
	"founder_title_3" text,
	"founder_bio_3" text,
	"founder_twitter_url_3" text,
	"founder_linkedin_url_3" text,
	"founder_first_name_4" text,
	"founder_last_name_4" text,
	"founder_title_4" text,
	"founder_bio_4" text,
	"founder_twitter_url_4" text,
	"founder_linkedin_url_4" text,
	"founder_first_name_5" text,
	"founder_last_name_5" text,
	"founder_title_5" text,
	"founder_bio_5" text,
	"founder_twitter_url_5" text,
	"founder_linkedin_url_5" text,
	"co_expected_valuation" integer,
	"co_fundraising_amount" integer,
	"co_past_fundraising_info" text,
	"co_funding_round" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "companies_AI" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"company_id" text,
	"co_industry_1" text,
	"co_industry_2" text,
	"co_industry_3" text,
	"co_one_liner" text,
	"co_target_region" text,
	"co_target_market" text,
	"co_description_1" text,
	"co_description_2" text,
	"co_description_3" text,
	"co_target_customer_profile" text,
	"co_customer_problem_1" text,
	"co_customer_problem_2" text,
	"co_customer_problem_3" text,
	"co_market_size" text,
	"co_market_landscape" text,
	"co_product_1" text,
	"co_product_2" text,
	"co_product_3" text,
	"co_differentation_1" text,
	"co_differentation_2" text,
	"co_differentation_3" text,
	"co_additional_notes" text,
	"co_executive_summary" text,
	"summary" text
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "companies_AI" ADD CONSTRAINT "companies_AI_company_id_companies_id_fk" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
