import { z } from "zod";

export const formSchema = z.object({
  coName: z.string().min(1, "Company Name is required"),
  coWebsiteUrl: z.string().url().optional(),
  noWebsite: z.boolean(),
  coIndustry1: z.string().optional(),
  coIndustry2: z.string().optional(),
  coIndustry3: z.string().optional(),
  coDescription: z.string().optional(),
  coOneLiner: z.string().min(1, "Company One-liner is required"),
  coCountry: z.string().min(1, "Country is required"),
  coCity: z.string().min(1, "City is required"),
  coProductStatus: z.string().min(1, "Product Status is required"),
  coCustomerCount: z.string().optional(),
  coMonthlyRevenue: z.string().optional(),
  coAnnualRevenue: z.string().optional(),
  coAnnualExpense: z.string().optional(),
  coExpectedValuation: z.number().int().optional(),
  coFundraisingAmount: z.number().int().optional(),
  coPastFundraisingInfo: z.string().optional(),
  coFundingRound: z.string().min(1, "Funding Round is required"),
  founderFirstName1: z.string().min(1, "First Name is required"),
  founderLastName1: z.string().min(1, "Last Name is required"),
  founderTitle1: z.string().min(1, "Title is required"),
  founderBio1: z.string().min(1, "Bio is required"),
  founderTwitterUrl1: z.string().url().optional(),
  founderLinkedinUrl1: z.string().url().optional(),
  founderFirstName2: z.string().optional(),
  founderLastName2: z.string().optional(),
  founderTitle2: z.string().optional(),
  founderBio2: z.string().optional(),
  founderTwitterUrl2: z.string().url().optional(),
  founderLinkedinUrl2: z.string().url().optional(),
  founderFirstName3: z.string().optional(),
  founderLastName3: z.string().optional(),
  founderTitle3: z.string().optional(),
  founderBio3: z.string().optional(),
  founderTwitterUrl3: z.string().url().optional(),
  founderLinkedinUrl3: z.string().url().optional(),
  founderFirstName4: z.string().optional(),
  founderLastName4: z.string().optional(),
  founderTitle4: z.string().optional(),
  founderBio4: z.string().optional(),
  founderTwitterUrl4: z.string().url().optional(),
  founderLinkedinUrl4: z.string().url().optional(),
  founderFirstName5: z.string().optional(),
  founderLastName5: z.string().optional(),
  founderTitle5: z.string().optional(),
  founderBio5: z.string().optional(),
  founderTwitterUrl5: z.string().url().optional(),
  founderLinkedinUrl5: z.string().url().optional(),
});
